export const UPLOAD_TODAY_PICTURE = "UPLOAD_TODAY_PICTURE";
export const UPLOAD_TODAY_PICTURE_SUCCESS = "UPLOAD_TODAY_PICTURE_SUCCESS";
export const UPLOAD_TODAY_PICTURE_FAILED = "UPLOAD_TODAY_PICTURE_FAILED"; 

export const UPLOAD_PICTURE = "UPLOAD_PICTURE";
export const UPLOAD_PICTURE_SUCCESS = "UPLOAD_PICTURE_SUCCESS";
export const UPLOAD_PICTURE_FAILED = "UPLOAD_PICTURE_FAILED";